// Supabase Dashboard → Project Settings → API
window.SUPABASE_URL = "https://nnumphbwhdjbwcdqjsli.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5udW1waGJ3aGRqYndjZHFqc2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNjQ0MzYsImV4cCI6MjA4Mjc0MDQzNn0.1atKwtpgJaDIPClt32MHee9Cr047URO48bPJg_z0uAY";
